apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress-nodeport-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 33001
  - name: https
    port: 443
    nodePort: 33002
  - name: https2
    port: 6443
    nodePort: 33003
  selector:
    run: haproxy-ingress
